global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
    - targets: ["localhost:9090"]
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['localhost:9464']
  - job_name: 'temporal-spring-boot'
    static_configs:
      - targets: ['localhost:8085']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 15s
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'temporal_.*'
        target_label: '__name__'
        replacement: '${1}'